name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Set this to your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_STORE_URL: ${{ secrets.VITE_STORE_URL }}
          VITE_CONSUMER_KEY: ${{ secrets.VITE_CONSUMER_KEY }}
          VITE_CONSUMER_SECRET: ${{ secrets.VITE_CONSUMER_SECRET }}
          VITE_AUTH_USERNAME: ${{ secrets.VITE_AUTH_USERNAME }}
          VITE_AUTH_PASSWORD: ${{ secrets.VITE_AUTH_PASSWORD }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
